Misure Qualità Prodotto
SweeTenTeam/Docs pull request #59
Opened 2024-11-26 16:19 UTC by orlifera

2024-11-26 19:57 UTC, MatteoCampa commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +  #align($"MD" = frac("DM", "TM") * 100$, center)
1207
#align($"MD" = frac("DM", "TM") * 100$, center) -> #align($"MD" = frac("NDM", "NTM") * 100$, center)

2024-11-26 19:57 UTC, MatteoCampa commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +- *M-PRD-CP* - Complessità Ciclomatica: valuta la complessità del sistema la attraverso la misurazione del numero di cammini indipendenti attraverso il grafo di controllo di flusso
1204
la attraverso la -> attraverso la

2024-11-26 19:57 UTC, MatteoCampa commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +- *M-PRD-FU* - Facilità Di Utilizzo: valutà la complessità di utilizzo del sistema
1195
valutà -> valuta

2024-11-26 19:57 UTC, MatteoCampa commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +  #align($"CRO" = frac("RO", "RT") * 100$, center)
1167
#align($"CRO" = frac("RO", "RT") * 100$, center) -> #align($"CRO" = frac("ROC", "ROT") * 100$, center)

2024-11-26 19:57 UTC, MatteoCampa commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +  #align($"CRD" = frac("RD", "RT") * 100$, center)
1163
#align($"CRD" = frac("RD", "RT") * 100$, center) -> #align($"CRD" = frac("RDC", "RDT") * 100$, center)

2024-11-26 19:57 UTC, MatteoCampa commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +  #align($"CRV" = frac("RV", "RT") * 100$, center)
1159
#align($"CRV" = frac("RV", "RT") * 100$, center) -> #align($"CRV" = frac("RVC", "RVT") * 100$, center)

2024-11-26 19:57 UTC, MatteoCampa commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +Come al paragrafo #link(<qualità_del_processo>, "precedente"), le metriche seguono la struttura definita al paragrafo #link(<metriche>, "'metriche'"). In questo capitolo, la prima parte della struttu
1154
*#align("M-PRD-[S.I.]", center)*. -> *#align("M-PRD-[S.I.]", center)*
(togliere il punto)

2024-11-26 19:57 UTC, MatteoCampa commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
>  Le metriche seguono la struttura definita a #link(<metriche>, "questo paragrafo"). In questo capitolo, la prima parte della struttura sarà: *M-PRC-[S.I.]*.
1101
*M-PRC-[S.I.]*. -> *#align("M-PRC-[S.I.]", center)*

2024-11-26 20:03 UTC, MatteoCampa requested changes
Per quanto riguarda le metriche dell'usabilità forse effettivamente si potrebbero aggiungere anche quelle presenti nel paragrafo degli standard; per gli altri paragrafi (affidabilità, funzionalità,...) non credo sia necessario.
Decidi te se metterle oppure no, secondo me in entrambi i casi va bene.

Per separare meglio le metriche sarebbe meglio anche aggiungere una riga vuota nel caso in cui da un sotto elenco puntato si passa a un elenco puntato
````
- elem 1
  - elem 1.1
  - elem 1.2

- elem 2
````
altrimenti è tutto troppo attaccato e si fa fatica a leggere

2024-11-27 10:33 UTC, orlifera commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +  #align($"MD" = frac("DM", "TM") * 100$, center)
Done

2024-11-27 10:33 UTC, orlifera commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +- *M-PRD-FU* - Facilità Di Utilizzo: valutà la complessità di utilizzo del sistema
done

2024-11-27 10:34 UTC, orlifera commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +- *M-PRD-CP* - Complessità Ciclomatica: valuta la complessità del sistema la attraverso la misurazione del numero di cammini indipendenti attraverso il grafo di controllo di flusso
done

2024-11-27 10:34 UTC, orlifera commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +  #align($"CRO" = frac("RO", "RT") * 100$, center)
done

2024-11-27 10:34 UTC, orlifera commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +  #align($"CRD" = frac("RD", "RT") * 100$, center)
done

2024-11-27 10:35 UTC, orlifera commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
> +  #align($"CRV" = frac("RV", "RT") * 100$, center)
done

2024-11-27 10:42 UTC, orlifera commented on documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
>  Le metriche seguono la struttura definita a #link(<metriche>, "questo paragrafo"). In questo capitolo, la prima parte della struttura sarà: *M-PRC-[S.I.]*.
done

2024-11-27 11:45 UTC, MatteoCampa approved these changes

2024-11-27 12:09 UTC, merged