Doc/glossario 83
SweeTenTeam/Docs pull request #85
Opened 2024-12-09 08:22 UTC by orlifera

close #83

2024-12-10 08:36 UTC, Valeryum999 commented on documents/2-RTB/Documentazione_Esterna/Glossario.typ
> +== #LTG("camleCase")
camleCase

2024-12-10 08:43 UTC, Valeryum999 requested changes
Fixa camleCase e il resto è tutto apposto

2024-12-10 10:12 UTC, orlifera commented on documents/2-RTB/Documentazione_Esterna/Glossario.typ
> +== #LTG("camleCase")
done

2024-12-10 10:14 UTC, orlifera commented
> Fixa camleCase e il resto è tutto apposto

done

2024-12-14 09:25 UTC, Valeryum999 approved these changes

2024-12-14 09:25 UTC, merged